set(DEFAULT_DEPLOY_PROJECT "${IP_FILTER}")

set(DEPLOY_PROJECT "${DEFAULT_DEPLOY_PROJECT}" CACHE STRING "${DEFAULT_DEPLOY_PROJECT}")

set_property(CACHE DEPLOY_PROJECT PROPERTY STRINGS "none" "${CICD}" "${IP_FILTER}")

set(DEPLOY_${CICD} OFF)
set(DEPLOY_${IP_FILTER} OFF)

if (NOT ${DEPLOY_PROJECT} STREQUAL "none")
	set(DEPLOY_${DEPLOY_PROJECT} ON)

	set(BUILD_${DEPLOY_PROJECT} ON CACHE BOOL "Build Deployment Project" FORCE)

	message(STATUS "Release package will be created for ${DEPLOY_PROJECT} project.")
endif()
