os: linux
dist: bionic
language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- sudo apt-get install libgtest-dev -y
- sudo apt-get install cmake -y
- mkdir temp
- cd temp
- cmake -DBUILD_SHARED_LIBS=ON /usr/src/gtest/
- cmake --build .
- sudo cp *.so /usr/lib
- rm -rf *
- cd ../doxygen
- sudo apt install graphviz -y
- sudo apt install ./doxygen_1.8.19_amd64.deb
- doxygen --version
- cd ..
script:
- cmake -DDEPLOY_PROJECT=$DEPLOYMENT_PROJECT_NAME -DTESTS_BOOST=ON .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen Doxyfile
branches:
  only:
    - gh-pages
    - master
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    local_dir: ./html
    keep_history: true
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script:
    - curl -T $DEPLOYMENT_PROJECT_NAME-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ujketra:$BINTRAY_API_KEY "https://api.bintray.com/content/jketra/otus_cpp/$DEPLOYMENT_PROJECT_NAME/$TRAVIS_BUILD_NUMBER/$DEPLOYMENT_PROJECT_NAME-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=$NEED_TO_PUBLISH"