os: linux
dist: bionic
language: cpp
addons:
  apt:
    packages:
      - doxygen
      - graphviz
before_script:
- sudo apt-get install libboost-test-dev -y
- sudo apt-get install libgtest-dev -y
- sudo apt-get install cmake -y
- mkdir gtest_temp
- cd gtest_temp
- cmake -DBUILD_SHARED_LIBS=ON /usr/src/gtest/
- cmake --build .
- sudo cp *.so /usr/lib
- cd ../
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cmake -DDEPLOY_PROJECT=$DEPLOYMENT_PROJECT_NAME .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen Doxyfile
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    local_dir: ./html
    keep_history: true
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script:
    - curl -T $DEPLOYMENT_PROJECT_NAME-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ujketra:$BINTRAY_API_KEY "https://api.bintray.com/content/jketra/otus_cpp/$DEPLOYMENT_PROJECT_NAME/$TRAVIS_BUILD_NUMBER/$DEPLOYMENT_PROJECT_NAME-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=$NEED_TO_PUBLISH"