language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- sudo apt-get install libgtest-dev -y
- sudo apt-get install cmake -y
- cd /usr/src/gtest/
- sudo cmake -DBUILD_SHARED_LIBS=ON
- sudo make
- sudo cp *.so /usr/lib
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T CICD-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ujketra:$BINTRAY_API_KEY "https://api.bintray.com/content/jketra/otus_cpp/CICD/$TRAVIS_BUILD_NUMBER/CICD-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64"
