# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/cmake-3.12.4/bin/cmake

# The command to remove a file.
RM = /usr/local/cmake-3.12.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/travis/build/jketra/otus_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/travis/build/jketra/otus_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/cmake-3.12.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/cmake-3.12.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/cmake-3.12.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/cmake-3.12.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/cmake-3.12.4/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/cmake-3.12.4/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/cmake-3.12.4/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/cmake-3.12.4/bin/cpack --config ./CPackSourceConfig.cmake /home/travis/build/jketra/otus_cpp/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/cmake-3.12.4/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/cmake-3.12.4/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/cmake-3.12.4/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/travis/build/jketra/otus_cpp/CMakeFiles /home/travis/build/jketra/otus_cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/travis/build/jketra/otus_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ProjectInfo

# Build rule for target.
ProjectInfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ProjectInfo
.PHONY : ProjectInfo

# fast build rule for target.
ProjectInfo/fast:
	$(MAKE) -f hw1_cicd/lib/CMakeFiles/ProjectInfo.dir/build.make hw1_cicd/lib/CMakeFiles/ProjectInfo.dir/build
.PHONY : ProjectInfo/fast

#=============================================================================
# Target rules for targets named HelloWorld

# Build rule for target.
HelloWorld: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HelloWorld
.PHONY : HelloWorld

# fast build rule for target.
HelloWorld/fast:
	$(MAKE) -f hw1_cicd/src/CMakeFiles/HelloWorld.dir/build.make hw1_cicd/src/CMakeFiles/HelloWorld.dir/build
.PHONY : HelloWorld/fast

#=============================================================================
# Target rules for targets named CicdGoogleTests

# Build rule for target.
CicdGoogleTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CicdGoogleTests
.PHONY : CicdGoogleTests

# fast build rule for target.
CicdGoogleTests/fast:
	$(MAKE) -f hw1_cicd/tests/GoogleTests/CMakeFiles/CicdGoogleTests.dir/build.make hw1_cicd/tests/GoogleTests/CMakeFiles/CicdGoogleTests.dir/build
.PHONY : CicdGoogleTests/fast

#=============================================================================
# Target rules for targets named IpFilter

# Build rule for target.
IpFilter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IpFilter
.PHONY : IpFilter

# fast build rule for target.
IpFilter/fast:
	$(MAKE) -f hw2_ip_filter/src/IpFilter/CMakeFiles/IpFilter.dir/build.make hw2_ip_filter/src/IpFilter/CMakeFiles/IpFilter.dir/build
.PHONY : IpFilter/fast

#=============================================================================
# Target rules for targets named RequiredOutputsModule

# Build rule for target.
RequiredOutputsModule: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RequiredOutputsModule
.PHONY : RequiredOutputsModule

# fast build rule for target.
RequiredOutputsModule/fast:
	$(MAKE) -f hw2_ip_filter/src/RequiredOutputsModule/CMakeFiles/RequiredOutputsModule.dir/build.make hw2_ip_filter/src/RequiredOutputsModule/CMakeFiles/RequiredOutputsModule.dir/build
.PHONY : RequiredOutputsModule/fast

#=============================================================================
# Target rules for targets named IpFilterTests

# Build rule for target.
IpFilterTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IpFilterTests
.PHONY : IpFilterTests

# fast build rule for target.
IpFilterTests/fast:
	$(MAKE) -f hw2_ip_filter/tests/IpFilterTests/CMakeFiles/IpFilterTests.dir/build.make hw2_ip_filter/tests/IpFilterTests/CMakeFiles/IpFilterTests.dir/build
.PHONY : IpFilterTests/fast

#=============================================================================
# Target rules for targets named PrintIp

# Build rule for target.
PrintIp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PrintIp
.PHONY : PrintIp

# fast build rule for target.
PrintIp/fast:
	$(MAKE) -f hw4_print_ip/src/PrintIp/CMakeFiles/PrintIp.dir/build.make hw4_print_ip/src/PrintIp/CMakeFiles/PrintIp.dir/build
.PHONY : PrintIp/fast

#=============================================================================
# Target rules for targets named PrintIpExample

# Build rule for target.
PrintIpExample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PrintIpExample
.PHONY : PrintIpExample

# fast build rule for target.
PrintIpExample/fast:
	$(MAKE) -f hw4_print_ip/src/PrintIpExample/CMakeFiles/PrintIpExample.dir/build.make hw4_print_ip/src/PrintIpExample/CMakeFiles/PrintIpExample.dir/build
.PHONY : PrintIpExample/fast

#=============================================================================
# Target rules for targets named PrintIpTests

# Build rule for target.
PrintIpTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PrintIpTests
.PHONY : PrintIpTests

# fast build rule for target.
PrintIpTests/fast:
	$(MAKE) -f hw4_print_ip/tests/PrintIpTests/CMakeFiles/PrintIpTests.dir/build.make hw4_print_ip/tests/PrintIpTests/CMakeFiles/PrintIpTests.dir/build
.PHONY : PrintIpTests/fast

#=============================================================================
# Target rules for targets named StringAddOns

# Build rule for target.
StringAddOns: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StringAddOns
.PHONY : StringAddOns

# fast build rule for target.
StringAddOns/fast:
	$(MAKE) -f libs/StringAddOns/CMakeFiles/StringAddOns.dir/build.make libs/StringAddOns/CMakeFiles/StringAddOns.dir/build
.PHONY : StringAddOns/fast

#=============================================================================
# Target rules for targets named OperationResult

# Build rule for target.
OperationResult: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OperationResult
.PHONY : OperationResult

# fast build rule for target.
OperationResult/fast:
	$(MAKE) -f libs/OperationResult/CMakeFiles/OperationResult.dir/build.make libs/OperationResult/CMakeFiles/OperationResult.dir/build
.PHONY : OperationResult/fast

#=============================================================================
# Target rules for targets named TypeTraits_lib

# Build rule for target.
TypeTraits_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TypeTraits_lib
.PHONY : TypeTraits_lib

# fast build rule for target.
TypeTraits_lib/fast:
	$(MAKE) -f libs/TypeTraits/CMakeFiles/TypeTraits_lib.dir/build.make libs/TypeTraits/CMakeFiles/TypeTraits_lib.dir/build
.PHONY : TypeTraits_lib/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... package_source"
	@echo "... edit_cache"
	@echo "... package"
	@echo "... test"
	@echo "... ProjectInfo"
	@echo "... HelloWorld"
	@echo "... CicdGoogleTests"
	@echo "... IpFilter"
	@echo "... RequiredOutputsModule"
	@echo "... IpFilterTests"
	@echo "... PrintIp"
	@echo "... PrintIpExample"
	@echo "... PrintIpTests"
	@echo "... StringAddOns"
	@echo "... OperationResult"
	@echo "... TypeTraits_lib"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

